### ISSUE TITLE
Sync error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation]

### ISSUE THREAD

**Issue by fredskis** [bakito/adguardhome-sync#295]
### What happened?

When adguardhome-sync runs, it seems to connect to the origin and replica correctly then has the following error: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8221aa]

goroutine 11 [running]:
github.com/bakito/adguardhome-sync/pkg/client.(*client).SetCustomRules(0xc0001625a0, 0x0)
        /home/bakito/go/src/github.com/bakito/adguardhome-sync/pkg/client/client.go:264 +0x2a
github.com/bakito/adguardhome-sync/pkg/sync.glob..func9(0xc0001455f0)
        /home/bakito/go/src/github.com/bakito/adguardhome-sync/pkg/sync/action-general.go:105 +0x1fc
github.com/bakito/adguardhome-sync/pkg/sync.(*defaultAction).sync(0xad5599?, 0x0?)
        /home/bakito/go/src/github.com/bakito/adguardhome-sync/pkg/sync/action.go:99 +0x1a
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).syncTo(0xc0004807c0, 0x424e9c?, 0xc0000fe280, {{0xc0002fa9d8, 0x13}, {0xc0002fa9d8, 0x13}, {0xad4742, 0x8}, {0xc000465440, ...}, ...})
        /home/bakito/go/src/github.com/bakito/adguardhome-sync/pkg/sync/sync.go:299 +0x8cd
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).sync(0xc0004807c0)
        /home/bakito/go/src/github.com/bakito/adguardhome-sync/pkg/sync/sync.go:259 +0x1670
github.com/bakito/adguardhome-sync/pkg/sync.Sync.func3()
        /home/bakito/go/src/github.com/bakito/adguardhome-sync/pkg/sync/sync.go:76 +0x6f
created by github.com/bakito/adguardhome-sync/pkg/sync.Sync in goroutine 1
        /home/bakito/go/src/github.com/bakito/adguardhome-sync/pkg/sync/sync.go:74 +0x74f
```

### AdguardHome-Sync Version

0.6.4
Using linuxserver.io's docker version in Unraid
Repository: lscr.io/linuxserver/adguardhome-sync:latest

### AdguardHome Version

Origin is LXC on Proxmox running: v0.107.43
Replica is docker container on Unraid running v0.107.43; repository: adguard/adguardhome

### Configuration

```shell
cron: "*/10 * * * *"

origin:
  url: http://10.10.10.1
  username: freddy
  password: redacted

replicas:
  - url: http://AdGuard-Home
    username: freddy
    password: redacted

api:
  port: 8080
  username: freddy
  password: redacted
```

### Current Applied Configuration

```shell
2024-02-04T16:25:37.728+1000    INFO    run     cmd/run.go:35   Printing adguardhome-sync config (THE APPLICATION WILL NOT START IN THIS MODE): 
origin:
    url: http://10.10.10.1
    webURL: http://10.10.10.1
    apiPath: /control
    username: freddy
    password: redacted
    insecureSkipVerify: false
    autoSetup: false
replicas:
    - url: http://AdGuard-Home
      webURL: http://AdGuard-Home
      apiPath: /control
      username: freddy
      password: redacted
      insecureSkipVerify: false
      autoSetup: false
cron: '*/10 * * * *'
runOnStart: true
printConfigOnly: true
api:
    port: 8080
    username: freddy
    password: redacted
features:
    dns:
        accessLists: true
        serverConfig: true
        rewrites: true
    dhcp:
        serverConfig: true
        staticLeases: true
    generalSettings: true
    queryLogConfig: true
    statsConfig: true
    clientSettings: true
    services: true
    filters: true
```

### Relevant log output

```shell
2024-02-04T16:28:11.708+1000    INFO    sync    sync/sync.go:38 AdGuardHome sync        {"version": "0.6.4", "build": "2024-01-31T17:49:23Z", "os": "linux", "arch": "amd64"}
2024-02-04T16:28:11.708+1000    DEBUG   sync    types/types.go:72       Using config    {"config": {"origin":{"url":"http://10.10.10.1","webURL":"http://10.10.10.1","apiPath":"/control","username":"f****y","password":"q****************************f","insecureSkipVerify":false,"autoSetup":false},"replicas":[{"url":"http://AdGuard-Home","webURL":"http://AdGuard-Home","apiPath":"/control","username":"f****y","password":"q****************************f","insecureSkipVerify":false,"autoSetup":false}],"cron":"*/10 * * * *","runOnStart":true,"api":{"port":8080,"username":"f****y","password":"i****************************r"},"features":{"dns":{"accessLists":true,"serverConfig":true,"rewrites":true},"dhcp":{"serverConfig":true,"staticLeases":true},"generalSettings":true,"queryLogConfig":true,"statsConfig":true,"clientSettings":true,"services":true,"filters":true}}}
2024-02-04T16:28:11.708+1000    INFO    sync    sync/sync.go:65 Setup cronjob   {"cron": "*/10 * * * *", "next-execution": "2024-02-04T16:30:00.000+1000"}
2024-02-04T16:28:11.708+1000    INFO    sync    sync/http.go:57 Starting API server     {"port": 8080}
2024-02-04T16:28:11.708+1000    INFO    sync    sync/sync.go:75 Running sync on startup
2024-02-04T16:28:11.708+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "10.10.10.1", "method": "GET", "path": "status", "username": "freddy"}
2024-02-04T16:28:11.765+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "10.10.10.1", "method": "GET", "path": "status", "username": "freddy", "status": 200, "body": "{\"version\":\"v0.107.43\",\"language\":\"\",\"dns_addresses\":[\"127.0.0.1\",\"::1\",\"10.10.10.1\",\"2403:580b:61:a::1\",\"fe80::be24:11ff:fe2a:6a3a%eth0\"],\"dns_port\":53,\"http_port\":80,\"protection_disabled_duration\":0,\"protection_enabled\":true,\"dhcp_available\":true,\"running\":true}\n", "content-type": ["application/json"]}
2024-02-04T16:28:11.765+1000    INFO    sync    sync/sync.go:172        Connected to origin     {"from": "10.10.10.1", "version": "v0.107.43"}
2024-02-04T16:28:11.765+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "10.10.10.1", "method": "GET", "path": "/profile", "username": "freddy"}
2024-02-04T16:28:11.879+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "10.10.10.1", "method": "GET", "path": "/profile", "username": "freddy", "status": 200, "body": "{\"name\":\"freddy\",\"language\":\"\",\"theme\":\"auto\"}\n", "content-type": ["application/json"]}
2024-02-04T16:28:11.879+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "10.10.10.1", "method": "GET", "path": "/parental/status", "username": "freddy"}
2024-02-04T16:28:11.938+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "10.10.10.1", "method": "GET", "path": "/parental/status", "username": "freddy", "status": 200, "body": "{\"enabled\":false}\n", "content-type": ["application/json"]}
2024-02-04T16:28:11.938+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "10.10.10.1", "method": "GET", "path": "/safesearch/status", "username": "freddy"}
2024-02-04T16:28:11.994+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "10.10.10.1", "method": "GET", "path": "/safesearch/status", "username": "freddy", "status": 200, "body": "{\"enabled\":false,\"bing\":true,\"duckduckgo\":true,\"google\":true,\"pixabay\":true,\"yandex\":true,\"youtube\":true}\n", "content-type": ["application/json"]}
2024-02-04T16:28:11.994+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "10.10.10.1", "method": "GET", "path": "/safebrowsing/status", "username": "freddy"}
2024-02-04T16:28:12.052+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "10.10.10.1", "method": "GET", "path": "/safebrowsing/status", "username": "freddy", "status": 200, "body": "{\"enabled\":false}\n", "content-type": ["application/json"]}
2024-02-04T16:28:12.052+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "10.10.10.1", "method": "GET", "path": "/rewrite/list", "username": "freddy"}
2024-02-04T16:28:12.109+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "10.10.10.1", "method": "GET", "path": "/rewrite/list", "username": "freddy", "status": 200, "body": "[]\n", "content-type": ["application/json"]}
2024-02-04T16:28:12.109+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "10.10.10.1", "method": "GET", "path": "/blocked_services/list", "username": "freddy"}
2024-02-04T16:28:12.167+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "10.10.10.1", "method": "GET", "path": "/blocked_services/list", "username": "freddy", "status": 200, "body": "[]\n", "content-type": ["application/json"]}
2024-02-04T16:28:12.167+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "10.10.10.1", "method": "GET", "path": "/blocked_services/get", "username": "freddy"}
2024-02-04T16:28:12.224+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "10.10.10.1", "method": "GET", "path": "/blocked_services/get", "username": "freddy", "status": 200, "body": "{\"schedule\":{\"time_zone\":\"Local\"},\"ids\":[]}\n", "content-type": ["application/json"]}
2024-02-04T16:28:12.224+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "10.10.10.1", "method": "GET", "path": "/filtering/status", "username": "freddy"}
2024-02-04T16:28:12.286+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "10.10.10.1", "method": "GET", "path": "/filtering/status", "username": "freddy", "status": 200, "body": "{\"filters\":[{\"url\":\"https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt\",\"name\":\"AdGuard DNS filter\",\"last_updated\":\"2024-02-04T08:30:44+10:00\",\"id\":1,\"rules_count\":61425,\"enabled\":true},{\"url\":\"https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt\",\"name\":\"AdAway Default Blocklist\",\"id\":2,\"rules_count\":0,\"enabled\":false}],\"whitelist_filters\":null,\"user_rules\":null,\"interval\":24,\"enabled\":true}\n", "content-type": ["application/json"]}
2024-02-04T16:28:12.286+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "10.10.10.1", "method": "GET", "path": "/clients", "username": "freddy"}
2024-02-04T16:28:12.343+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "10.10.10.1", "method": "GET", "path": "/clients", "username": "freddy", "status": 200, "body": "{\"clients\":null,\"auto_clients\":[{\"whois_info\":{\"country\":\"AU\",\"orgname\":\"widebandnetv6\"},\"ip\":\"2403:580b:61:a:a494:baad:4d5:6d9a\",\"name\":\"2403-580b-61-a-a494-baad-4d5-6d9a.ip6.aussiebb.net\",\"source\":\"rDNS\"},{\"whois_info\":{\"country\":\"AU\",\"orgname\":\"widebandnetv6\"},\"ip\":\"2403:580b:61:a:18fd:273:1455:ce24\",\"name\":\"2403-580b-61-a-18fd-273-1455-ce24.ip6.aussiebb.net\",\"source\":\"rDNS\"},{\"whois_info\":{},\"ip\":\"10.10.10.53\",\"name\":\"LGwebOSTV.ad.redhax.com\",\"source\":\"rDNS\"},{\"whois_info\":{\"country\":\"AU\",\"orgname\":\"widebandnetv6\"},\"ip\":\"2403:580b:61:a:64e:afff:fe28:fa10\",\"name\":\"2403-580b-61-a-64e-afff-fe28-fa10.ip6.aussiebb.net\",\"source\":\"rDNS\"},{\"whois_info\":{},\"ip\":\"10.10.10.10\",\"name\":\"\",\"source\":\"ARP\"},{\"whois_info\":{},\"ip\":\"10.10.10.68\",\"name\":\"\",\"source\":\"ARP\"},{\"whois_info\":{\"country\":\"AU\",\"orgname\":\"widebandnetv6\"},\"ip\":\"2403:580b:61:a:207a:a166:b9c0:2eb8\",\"name\":\"2403-580b-61-a-207a-a166-b9c0-2eb8.ip6.aussiebb.net\",\"source\":\"rDNS\"},{\"whois_info\":{},\"ip\":\"10.10.10.221\",\"name\":\"app.ad.redhax.com\",\"source\":\"rDNS\"},{\"whois_info\":{},\"ip\":\"10.10.10.12\",\"name\":\"dc2.ad.redhax.com\",\"source\":\"rDNS\"},{\"whois_info\":{},\"ip\":\"10.10.10.11\",\"name\":\"\",\"source\":\"ARP\"},{\"whois_info\":{},\"ip\":\"10.10.10.250\",\"name\":\"\",\"source\":\"ARP\"},{\"whois_info\":{},\"ip\":\"10.10.10.122\",\"name\":\"pc.ad.redhax.com\",\"source\":\"rDNS\"},{\"whois_info\":{},\"ip\":\"10.10.10.13\",\"name\":\"\",\"source\":\"ARP\"},{\"whois_info\":{\"country\":\"AU\",\"orgname\":\"widebandnetv6\"},\"ip\":\"2403:580b:61:a:1da5:888f:b143:8eeb\",\"name\":\"2403-580b-61-a-1da5-888f-b143-8eeb.ip6.aussiebb.net\",\"source\":\"rDNS\"}],\"supported_tags\":[\"device_audio\",\"device_camera\",\"device_gameconsole\",\"device_laptop\",\"device_nas\",\"device_other\",\"device_pc\",\"device_phone\",\"device_printer\",\"device_securityalarm\",\"device_tablet\",\"device_tv\",\"os_android\",\"os_ios\",\"os_linux\",\"os_macos\",\"os_other\",\"os_windows\",\"user_admin\",\"user_child\",\"user_regular\"]}\n", "content-type": ["application/json"]}
2024-02-04T16:28:12.343+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "10.10.10.1", "method": "GET", "path": "/querylog_info", "username": "freddy"}
2024-02-04T16:28:12.402+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "10.10.10.1", "method": "GET", "path": "/querylog_info", "username": "freddy", "status": 200, "body": "{\"interval\":90,\"enabled\":true,\"anonymize_client_ip\":false}\n", "content-type": ["application/json"]}
2024-02-04T16:28:12.402+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "10.10.10.1", "method": "GET", "path": "/stats_info", "username": "freddy"}
2024-02-04T16:28:12.459+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "10.10.10.1", "method": "GET", "path": "/stats_info", "username": "freddy", "status": 200, "body": "{\"interval\":1}\n", "content-type": ["application/json"]}
2024-02-04T16:28:12.459+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "10.10.10.1", "method": "GET", "path": "/access/list", "username": "freddy"}
2024-02-04T16:28:12.517+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "10.10.10.1", "method": "GET", "path": "/access/list", "username": "freddy", "status": 200, "body": "{\"allowed_clients\":null,\"disallowed_clients\":null,\"blocked_hosts\":[\"version.bind\",\"id.server\",\"hostname.bind\"]}\n", "content-type": ["application/json"]}
2024-02-04T16:28:12.517+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "10.10.10.1", "method": "GET", "path": "/dns_info", "username": "freddy"}
2024-02-04T16:28:12.574+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "10.10.10.1", "method": "GET", "path": "/dns_info", "username": "freddy", "status": 200, "body": "{\"upstream_dns\":[\"https://dns10.quad9.net/dns-query\",\"[/lab.redhax.com/]2403:580b:61:b::b 2403:580b:61:b::c 10.10.11.11 10.10.11.12\",\"[/ad.redhax.com/redhax.com/]2403:580b:61:a::b 2403:580b:61:a::c 2403:580b:61:a::d 10.10.10.11 10.10.10.12 10.10.10.13\"],\"upstream_dns_file\":\"\",\"bootstrap_dns\":[\"9.9.9.10\",\"149.112.112.10\",\"2620:fe::10\",\"2620:fe::fe:10\"],\"fallback_dns\":[],\"protection_enabled\":true,\"ratelimit\":20,\"ratelimit_subnet_len_ipv4\":24,\"ratelimit_subnet_len_ipv6\":56,\"ratelimit_whitelist\":[],\"blocking_mode\":\"default\",\"edns_cs_enabled\":false,\"edns_cs_use_custom\":false,\"dnssec_enabled\":false,\"disable_ipv6\":false,\"upstream_mode\":\"\",\"blocked_response_ttl\":10,\"cache_size\":4194304,\"cache_ttl_min\":0,\"cache_ttl_max\":0,\"cache_optimistic\":false,\"resolve_clients\":true,\"use_private_ptr_resolvers\":true,\"local_ptr_upstreams\":[],\"blocking_ipv4\":\"\",\"blocking_ipv6\":\"\",\"protection_disabled_until\":null,\"edns_cs_custom_ip\":\"\",\"default_local_ptr_upstreams\":[\"10.10.10.11:53\",\"10.10.10.12:53\",\"10.10.10.13:53\"]}\n", "content-type": ["application/json"]}
2024-02-04T16:28:12.574+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "10.10.10.1", "method": "GET", "path": "/dhcp/status", "username": "freddy"}
2024-02-04T16:28:12.633+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "10.10.10.1", "method": "GET", "path": "/dhcp/status", "username": "freddy", "status": 200, "body": "{\"interface_name\":\"\",\"v4\":{\"gateway_ip\":\"\",\"subnet_mask\":\"\",\"range_start\":\"\",\"range_end\":\"\",\"lease_duration\":0},\"v6\":{\"range_start\":\"\",\"lease_duration\":86400},\"leases\":[],\"static_leases\":[],\"enabled\":false}\n", "content-type": ["application/json"]}
2024-02-04T16:28:12.633+1000    INFO    sync    sync/sync.go:271        Start sync      {"from": "10.10.10.1", "to": "AdGuard-Home"}
2024-02-04T16:28:12.633+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "AdGuard-Home", "method": "GET", "path": "status", "username": "freddy"}
2024-02-04T16:28:12.683+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "AdGuard-Home", "method": "GET", "path": "status", "username": "freddy", "status": 200, "body": "{\"version\":\"v0.107.43\",\"language\":\"\",\"dns_addresses\":[\"127.0.0.1\",\"::1\",\"172.28.0.2\",\"10.10.10.2\",\"2403:580b:61:a:8bf:b800:16c:5e40\",\"2403:580b:61:a::2\",\"fe80::8bf:b800:16c:5e40%eth0\"],\"dns_port\":53,\"http_port\":80,\"protection_disabled_duration\":0,\"protection_enabled\":true,\"dhcp_available\":true,\"running\":true}\n", "content-type": ["application/json"]}
2024-02-04T16:28:12.683+1000    INFO    sync    sync/sync.go:279        Connected to replica    {"from": "10.10.10.1", "to": "AdGuard-Home", "version": "v0.107.43"}
2024-02-04T16:28:12.683+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "AdGuard-Home", "method": "GET", "path": "/profile", "username": "freddy"}
2024-02-04T16:28:12.784+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "AdGuard-Home", "method": "GET", "path": "/profile", "username": "freddy", "status": 200, "body": "{\"name\":\"freddy\",\"language\":\"\",\"theme\":\"auto\"}\n", "content-type": ["application/json"]}
2024-02-04T16:28:12.784+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "AdGuard-Home", "method": "GET", "path": "/parental/status", "username": "freddy"}
2024-02-04T16:28:12.834+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "AdGuard-Home", "method": "GET", "path": "/parental/status", "username": "freddy", "status": 200, "body": "{\"enabled\":false}\n", "content-type": ["application/json"]}
2024-02-04T16:28:12.834+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "AdGuard-Home", "method": "GET", "path": "/safesearch/status", "username": "freddy"}
2024-02-04T16:28:12.884+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "AdGuard-Home", "method": "GET", "path": "/safesearch/status", "username": "freddy", "status": 200, "body": "{\"enabled\":false,\"bing\":true,\"duckduckgo\":true,\"google\":true,\"pixabay\":true,\"yandex\":true,\"youtube\":true}\n", "content-type": ["application/json"]}
2024-02-04T16:28:12.884+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "AdGuard-Home", "method": "GET", "path": "/safebrowsing/status", "username": "freddy"}
2024-02-04T16:28:12.932+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "AdGuard-Home", "method": "GET", "path": "/safebrowsing/status", "username": "freddy", "status": 200, "body": "{\"enabled\":false}\n", "content-type": ["application/json"]}
2024-02-04T16:28:12.932+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "AdGuard-Home", "method": "GET", "path": "/querylog_info", "username": "freddy"}
2024-02-04T16:28:12.981+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "AdGuard-Home", "method": "GET", "path": "/querylog_info", "username": "freddy", "status": 200, "body": "{\"interval\":90,\"enabled\":true,\"anonymize_client_ip\":false}\n", "content-type": ["application/json"]}
2024-02-04T16:28:12.981+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "AdGuard-Home", "method": "GET", "path": "/stats_info", "username": "freddy"}
2024-02-04T16:28:13.030+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "AdGuard-Home", "method": "GET", "path": "/stats_info", "username": "freddy", "status": 200, "body": "{\"interval\":1}\n", "content-type": ["application/json"]}
2024-02-04T16:28:13.030+1000    INFO    client  client/client.go:337    Set stats config        {"host": "AdGuard-Home", "interval": 1}
2024-02-04T16:28:13.030+1000    DEBUG   client  client/client-methods.go:50     do post {"host": "AdGuard-Home", "method": "POST", "path": "/stats_config", "username": "freddy", "body": "{\"interval\":1}"}
2024-02-04T16:28:13.082+1000    DEBUG   client  client/client-methods.go:63     got response    {"host": "AdGuard-Home", "method": "POST", "path": "/stats_config", "username": "freddy", "status": 200, "body": "", "content-type": ""}
2024-02-04T16:28:13.082+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "AdGuard-Home", "method": "GET", "path": "/rewrite/list", "username": "freddy"}
2024-02-04T16:28:13.133+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "AdGuard-Home", "method": "GET", "path": "/rewrite/list", "username": "freddy", "status": 200, "body": "[]\n", "content-type": ["application/json"]}
2024-02-04T16:28:13.133+1000    DEBUG   client  client/client-methods.go:17     do get  {"host": "AdGuard-Home", "method": "GET", "path": "/filtering/status", "username": "freddy"}
2024-02-04T16:28:13.181+1000    DEBUG   client  client/client-methods.go:37     got response    {"host": "AdGuard-Home", "method": "GET", "path": "/filtering/status", "username": "freddy", "status": 200, "body": "{\"filters\":[{\"url\":\"https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt\",\"name\":\"AdGuard DNS filter\",\"last_updated\":\"2024-02-04T10:29:22+10:00\",\"id\":1,\"rules_count\":61470,\"enabled\":true},{\"url\":\"https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt\",\"name\":\"AdAway Default Blocklist\",\"id\":2,\"rules_count\":0,\"enabled\":false}],\"whitelist_filters\":null,\"user_rules\":[],\"interval\":24,\"enabled\":true}\n", "content-type": ["application/json"]}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8221aa]

goroutine 10 [running]:
github.com/bakito/adguardhome-sync/pkg/client.(*client).SetCustomRules(0xc000394720, 0x0)
        /home/bakito/go/src/github.com/bakito/adguardhome-sync/pkg/client/client.go:264 +0x2a
github.com/bakito/adguardhome-sync/pkg/sync.glob..func9(0xc00048fa00)
        /home/bakito/go/src/github.com/bakito/adguardhome-sync/pkg/sync/action-general.go:105 +0x1fc
github.com/bakito/adguardhome-sync/pkg/sync.(*defaultAction).sync(0xad5599?, 0x0?)
        /home/bakito/go/src/github.com/bakito/adguardhome-sync/pkg/sync/action.go:99 +0x1a
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).syncTo(0xc000136280, 0x424e9c?, 0xc00043e200, {{0xc0002fc9d8, 0x13}, {0xc0002fc9d8, 0x13}, {0xad4742, 0x8}, {0xc000467448, ...}, ...})
        /home/bakito/go/src/github.com/bakito/adguardhome-sync/pkg/sync/sync.go:299 +0x8cd
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).sync(0xc000136280)
        /home/bakito/go/src/github.com/bakito/adguardhome-sync/pkg/sync/sync.go:259 +0x1670
github.com/bakito/adguardhome-sync/pkg/sync.Sync.func3()
        /home/bakito/go/src/github.com/bakito/adguardhome-sync/pkg/sync/sync.go:76 +0x6f
created by github.com/bakito/adguardhome-sync/pkg/sync.Sync in goroutine 1
        /home/bakito/go/src/github.com/bakito/adguardhome-sync/pkg/sync/sync.go:74 +0x74f
```

### Anything else?

I have confirmed I can reach both machines, origin: 10.10.10.1 and replica: AdGuard-Home (also the internal 172.* docker IP) from the adguardhome-sync container shell to rule out networking. 
I have also configured Heimdall container with the same network settings as adguardhome-sync and entered the same origin and replica URLs and credentials to test and confirm the API is working to both AdGuard Home instances correctly.

**Comment by bakito** [comment]
@fredskis The possible could be identified.
It seems to be a problem with empty user filter rules. 
Until the fix can be tested and released, you could try to add atl least one user filter rule and check if this fixes the problem.

**Comment by bakito** [comment]
The newest main image should fix the issue. 
https://github.com/bakito/adguardhome-sync/pkgs/container/adguardhome-sync/174577877?tag=main
@fredskis could you please verify?

**Comment by fredskis** [comment]
Thank you for the very prompt troubleshooting and fix! 
I've switched over my image source to: ghcr.io/bakito/adguardhome-sync:main
and it looks like sync is now working fine!

```
2024-02-04T18:25:33.761+1000    INFO    sync    sync/sync.go:38 AdGuardHome sync        {"version": "main", "build": "2024-02-04T07:58:54Z", "os": "linux", "arch": "amd64"}
2024-02-04T18:25:33.762+1000    INFO    sync    sync/sync.go:65 Setup cronjob   {"cron": "*/10 * * * *", "next-execution": "2024-02-04T18:30:00.000+1000"}
2024-02-04T18:25:33.762+1000    INFO    sync    sync/http.go:57 Starting API server     {"port": 8080}
2024-02-04T18:25:33.762+1000    INFO    sync    sync/sync.go:75 Running sync on startup
2024-02-04T18:25:33.815+1000    INFO    sync    sync/sync.go:172        Connected to origin     {"from": "10.10.10.1", "version": "v0.107.43"}
2024-02-04T18:25:34.602+1000    INFO    sync    sync/sync.go:271        Start sync      {"from": "10.10.10.1", "to": "AdGuard-Home"}
2024-02-04T18:25:34.651+1000    INFO    sync    sync/sync.go:279        Connected to replica    {"from": "10.10.10.1", "to": "AdGuard-Home", "version": "v0.107.43"}
2024-02-04T18:25:35.002+1000    INFO    client  client/client.go:341    Set stats config        {"host": "AdGuard-Home", "interval": 1}
2024-02-04T18:25:35.156+1000    INFO    client  client/client.go:273    Toggle filtering        {"host": "AdGuard-Home", "enabled": true, "interval": 24}
2024-02-04T18:25:35.313+1000    INFO    client  client/client.go:298    Set blocked services schedule   {"host": "AdGuard-Home", "services": "[]"}
2024-02-04T18:25:35.562+1000    INFO    sync    sync/sync.go:307        Sync done       {"from": "10.10.10.1", "to": "AdGuard-Home"}
```

**Comment by bakito** [comment]
@fredskis this is released in https://github.com/bakito/adguardhome-sync/releases/tag/v0.6.5
